### ISSUE TITLE
The option to change the photo

### ISSUE THREAD

**Issue by dleonard00** [dleonard00/dexy#14]

**Comment by dleonard00** [comment]
can you make this one more descriptive for me? @mchris32

**Comment by mchris32** [comment]
When clicking on a cover photo for an address list, the user would be able to change which cover photo is showing the very same as someone could switch their profile cover photo on their personal profile. You can use Instagram as a reference.

**Comment by dleonard00** [comment]
perfect thanks!

**Comment by mchris32** [comment]
How would you rate this?
